language: java
dist: xenial
env:
 global:
  - SONAR_TOKEN=99450b20c9fee3d54e02b007eb6f2729772048b5
jdk:
 - openjdk11
cache:
 directories:
  - $HOME/.m2/
services:
 - mysql
before_install:
 - mysql -e 'CREATE USER "root01"@"localhost" IDENTIFIED BY "root";'
 - mysql -e 'GRANT ALL PRIVILEGES ON * . * TO "root01"@"localhost";'
 - mysql -e 'CREATE DATABASE IF NOT EXISTS medico;'
addons:
 sonarcloud:
  organization: "vishalsonar"
script: mvn clean install sonar:sonar -Dsonar.projectKey=vishalsonar_medico -DskipTests=true -Dmaven.javadoc.skip=true -B -V
notification:
 email: vsonar908@gmail.com
